# Generated by Django 4.0 on 2022-01-16 09:28

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('activities', multiselectfield.db.fields.MultiSelectField(choices=[('hiking', 'hiking'), ('Boat Riding', 'Boat Riding'), ('Board Games', 'Board Games'), ('Bonfire', 'Bonfire'), ('Swimming', 'Swimming')], max_length=47)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trip.category')),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
    ]
